import Foundation
import HealthCore

/// Credential lookup, in priority order:
/// 1. Bundled Secrets.plist (gitignored; generated by Scripts/secrets.sh from .env.local)
///    — works when the app is launched standalone from the home screen.
/// 2. Environment variables — works for Xcode-launched runs and simulator
///    launches with env passthrough.
enum Secrets {
    private static var plist: NSDictionary? {
        guard let url = Bundle.main.url(forResource: "Secrets", withExtension: "plist") else { return nil }
        return NSDictionary(contentsOf: url)
    }

    private static func value(_ key: String) -> String? {
        if let v = plist?[key] as? String, !v.isEmpty { return v }
        if let v = ProcessInfo.processInfo.environment[key], !v.isEmpty { return v }
        return nil
    }

    /// Azure OpenAI is the primary provider (Gary's Azure credits); Claude is
    /// used if only an Anthropic key is configured.
    static func makeIntelligence() -> (any IntelligenceService)? {
        if let endpoint = value("AZURE_OPENAI_ENDPOINT").flatMap(URL.init(string:)),
           let key = value("AZURE_OPENAI_KEY"),
           let deployment = value("AZURE_OPENAI_DEPLOYMENT") {
            return AzureOpenAIIntelligence(endpoint: endpoint, apiKey: key, deployment: deployment)
        }
        if let key = value("ANTHROPIC_API_KEY"), key.hasPrefix("sk-ant") {
            return ClaudeIntelligence(apiKey: key)
        }
        return nil
    }

    static var elevenLabsAPIKey: String? { value("ELEVENLABS_API_KEY") }
}
